version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'springboot_mysql_example'
      MYSQL_USER: 'newuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  java:
    build:
     context: .
     dockerfile: Dockerjava
    ports:
       - '8080:8080'
    volumes:
      - .:/usr/src/app
  nodejs:
    environment:
     API_HOST: 'http://java:8080'
    build:
        context: .
        dockerfile: Dockernodejs
    ports:
       - '3000:3000'
    volumes:
      - ./nodebuild/web:/usr/src/app
